import {Fuel,Settings,Vessel,Year,YEARS} from './types';
const rec=(a:number,b:number,c:number,d:number)=>({2030:a,2035:b,2040:c,2050:d} as Record<Year,number>);
const FX=1.08;
const series=(usdT:Record<Year,number>,lcv:number)=>({usdT,eurT:Object.fromEntries(YEARS.map(y=>[y,usdT[y]/FX])) as Record<Year,number>,eurGJ:Object.fromEntries(YEARS.map(y=>[y,usdT[y]/FX/lcv])) as Record<Year,number>});
const p=(values:[number,number,number,number],lcv:number,low=.8,high=1.2)=>{const base=rec(...values),lo=rec(...values.map(v=>v*low) as [number,number,number,number]),hi=rec(...values.map(v=>v*high) as [number,number,number,number]);return{...series(base,lcv),low:series(lo,lcv),high:series(hi,lcv)}};
export const settings:Settings={baseCI:91.16,reduction:rec(.06,.145,.31,.80),penaltyRate:2400,eurUsd:1.08,year:2030,scenario:'Base',eua:{Low:rec(70,80,95,120),Base:rec(100,120,150,200),High:rec(140,180,230,300)},rfNboIncentive:true,rfNboSubtarget:false,reward:2,rewardFrom:2025,rewardTo:2033,gwpCH4:28,gwpN2O:265,etsSurrender:1,lngSlip:{'LNG Otto LP':.035,'LNG Otto medium speed':.025,'LNG diesel cycle':.006,'LNG high pressure dual fuel':.002,'User Defined':.02}};
export const fuels:Fuel[]=[
 {id:'vlsfo',name:'VLSFO',lcv:40.5,ci:91.16,wtt:13.5,co2:3.114,ch4:0,n2o:0,slip:0,price:p([650,650,660,670],40.5),priceBasis:'USD/t',priceSource:'Market benchmark planning assumption',priceBasisNote:'Long-term commodity comparator; not a point forecast',priceConfidence:'Medium',rfnbo:false,bio:false,food:false,eligible:true,maxSupply:1e9,maxBlend:1,minBlend:0,pilotShare:0,pilotFuel:'vlsfo'},
 {id:'lng',name:'LNG',lcv:49.1,ci:75,wtt:18.5,co2:2.75,ch4:0,n2o:0,slip:.035,price:p([720,700,690,680],49.1),priceBasis:'USD/t',priceSource:'Market benchmark planning assumption',priceBasisNote:'Commodity comparator without clean-fuel learning curve',priceConfidence:'Medium',rfnbo:false,bio:false,food:false,eligible:true,maxSupply:1e9,maxBlend:1,minBlend:0,pilotShare:0,pilotFuel:'vlsfo'},
 {id:'cellulosic',name:'Cellulosic Bio-Methanol',lcv:19.9,ci:18,wtt:15,co2:0.08,ch4:0,n2o:0,slip:0,price:p([700,650,610,570],19.9),priceBasis:'USD/t',priceSource:'IRENA Renewable Methanol',priceBasisNote:'Residue feedstock scale-up planning assumption',priceConfidence:'Medium',rfnbo:false,bio:true,food:false,eligible:true,maxSupply:200000,maxBlend:1,minBlend:0,pilotShare:0,pilotFuel:'vlsfo'},
 {id:'foodBio',name:'Food Bio-Methanol',lcv:19.9,ci:45,wtt:35,co2:.2,ch4:0,n2o:0,slip:0,price:p([720,710,700,700],19.9,.9,1.25),priceBasis:'USD/t',priceSource:'Public biofuel cost ranges',priceBasisNote:'Feedstock scarcity and sustainability constraints',priceConfidence:'Low',rfnbo:false,bio:true,food:true,eligible:false,maxSupply:100000,maxBlend:1,minBlend:0,pilotShare:0,pilotFuel:'vlsfo'},
 {id:'eMethanol',name:'e-Methanol',lcv:19.9,ci:12,wtt:9,co2:.04,ch4:0,n2o:0,slip:0,price:p([750,680,610,520],19.9),priceBasis:'USD/t',priceSource:'IRENA Renewable Methanol + S&P Global cross-check',priceBasisNote:'Technology learning and scale-up; current market indications are only a sanity check',priceConfidence:'Medium',rfnbo:true,bio:false,food:false,eligible:true,maxSupply:250000,maxBlend:1,minBlend:0,pilotShare:0,pilotFuel:'vlsfo'},
 {id:'ammonia',name:'Green Ammonia',lcv:18.6,ci:9,wtt:7,co2:0,ch4:0,n2o:.0001,slip:0,price:p([600,540,490,430],18.6),priceBasis:'USD/t',priceSource:'IEA low-carbon fuels + S&P Global cross-check',priceBasisNote:'Electrolyser, renewable power and scale improvement',priceConfidence:'Medium',rfnbo:true,bio:false,food:false,eligible:true,maxSupply:250000,maxBlend:1,minBlend:0,pilotShare:.05,pilotFuel:'vlsfo'},
 {id:'blueMethanol',name:'Blue Methanol',lcv:19.9,ci:48,wtt:40,co2:.15,ch4:0,n2o:0,slip:0,price:p([650,620,590,560],19.9),priceBasis:'USD/t',priceSource:'Public CCS and natural-gas pathway ranges',priceBasisNote:'Lower learning rate than renewable e-fuels',priceConfidence:'Low',rfnbo:false,bio:false,food:false,eligible:true,maxSupply:180000,maxBlend:1,minBlend:0,pilotShare:0,pilotFuel:'vlsfo',blue:{upstream:12,production:55,capture:.9,residual:5.5,leakage:3,transport:2,advanced:false}}
];
export const makeVessels=(n=10):Vessel[]=>(Array.from({length:n},(_,i)=>({id:crypto.randomUUID(),name:`Vessel ${i+1}`,energyGJ:405000,route:'Intra-EU',etsScope:1,fuelEUScope:1,engine:'LNG Otto LP',compatible:fuels.map(f=>f.id),ready:true,maxBlend:1,mix:{vlsfo:1}})));
